"""
浦和カップ SDK生成エージェント - Issue管理
"""

import json
from datetime import datetime
from pathlib import Path
from typing import List, Optional
from dataclasses import dataclass, asdict

import sys
sys.path.insert(0, str(Path(__file__).parent.parent))

from config import ISSUE_DIR, LOG_DIR


@dataclass
class Issue:
    """Issue定義"""
    id: int
    title: str
    description: str
    category: str  # "architecture", "code", "test", "documentation"
    severity: str  # "critical", "high", "medium", "low"
    status: str  # "open", "in_progress", "resolved", "closed"
    location: Optional[str] = None
    fix_suggestion: Optional[str] = None
    created_at: str = ""
    updated_at: str = ""
    resolved_at: Optional[str] = None

    def __post_init__(self):
        if not self.created_at:
            self.created_at = datetime.now().isoformat()
        if not self.updated_at:
            self.updated_at = self.created_at


class IssueManager:
    """Issue管理クラス"""

    def __init__(self):
        self.issues: List[Issue] = []
        self.issue_file = ISSUE_DIR / "AutoGeneratedIssues.json"
        self.markdown_file = ISSUE_DIR / "AutoGeneratedIssues.md"
        self._load_issues()

    def _load_issues(self):
        """既存Issueを読み込み"""
        if self.issue_file.exists():
            try:
                data = json.loads(self.issue_file.read_text(encoding="utf-8"))
                self.issues = [Issue(**item) for item in data]
            except (json.JSONDecodeError, TypeError):
                self.issues = []

    def _save_issues(self):
        """Issueを保存"""
        ISSUE_DIR.mkdir(exist_ok=True)

        # JSON保存
        data = [asdict(issue) for issue in self.issues]
        self.issue_file.write_text(
            json.dumps(data, ensure_ascii=False, indent=2),
            encoding="utf-8"
        )

        # Markdown保存
        self._save_markdown()

    def _save_markdown(self):
        """MarkdownフォーマットでIssue一覧を保存"""
        content = "# 自動生成Issue一覧\n\n"
        content += f"最終更新: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"

        # カテゴリ別に分類
        categories = {}
        for issue in self.issues:
            if issue.category not in categories:
                categories[issue.category] = []
            categories[issue.category].append(issue)

        # Open Issues
        open_issues = [i for i in self.issues if i.status in ("open", "in_progress")]
        content += f"## Open Issues ({len(open_issues)})\n\n"

        for category, issues in categories.items():
            category_open = [i for i in issues if i.status in ("open", "in_progress")]
            if category_open:
                content += f"### {category.upper()}\n\n"
                for issue in category_open:
                    status_badge = "🔴" if issue.severity == "critical" else "🟠" if issue.severity == "high" else "🟡"
                    content += f"#### {status_badge} Issue #{issue.id:03d}: {issue.title}\n"
                    content += f"- **深刻度**: {issue.severity}\n"
                    content += f"- **ステータス**: {issue.status}\n"
                    if issue.location:
                        content += f"- **場所**: `{issue.location}`\n"
                    content += f"- **説明**: {issue.description}\n"
                    if issue.fix_suggestion:
                        content += f"- **修正案**: {issue.fix_suggestion}\n"
                    content += "\n"

        # Resolved Issues
        resolved = [i for i in self.issues if i.status in ("resolved", "closed")]
        content += f"\n## Resolved Issues ({len(resolved)})\n\n"
        for issue in resolved:
            content += f"- ~~Issue #{issue.id:03d}: {issue.title}~~ (解決: {issue.resolved_at or 'N/A'})\n"

        self.markdown_file.write_text(content, encoding="utf-8")

    def create_issue(
        self,
        title: str,
        description: str,
        category: str,
        severity: str = "medium",
        location: Optional[str] = None,
        fix_suggestion: Optional[str] = None,
    ) -> Issue:
        """新規Issueを作成"""
        issue_id = max((i.id for i in self.issues), default=0) + 1

        issue = Issue(
            id=issue_id,
            title=title,
            description=description,
            category=category,
            severity=severity,
            status="open",
            location=location,
            fix_suggestion=fix_suggestion,
        )

        self.issues.append(issue)
        self._save_issues()

        return issue

    def update_status(self, issue_id: int, status: str):
        """Issueステータスを更新"""
        for issue in self.issues:
            if issue.id == issue_id:
                issue.status = status
                issue.updated_at = datetime.now().isoformat()
                if status in ("resolved", "closed"):
                    issue.resolved_at = datetime.now().isoformat()
                break
        self._save_issues()

    def get_open_issues(self, category: Optional[str] = None) -> List[Issue]:
        """Open Issueを取得"""
        issues = [i for i in self.issues if i.status in ("open", "in_progress")]
        if category:
            issues = [i for i in issues if i.category == category]
        return issues

    def get_critical_issues(self) -> List[Issue]:
        """重要度が高いIssueを取得"""
        return [
            i for i in self.issues
            if i.status in ("open", "in_progress") and i.severity in ("critical", "high")
        ]

    def create_architecture_violation_issue(
        self,
        rule_name: str,
        description: str,
        location: str,
        fix_suggestion: str,
    ) -> Issue:
        """アーキテクチャ違反Issueを作成"""
        return self.create_issue(
            title=f"アーキテクチャ違反: {rule_name}",
            description=description,
            category="architecture",
            severity="high",
            location=location,
            fix_suggestion=fix_suggestion,
        )


if __name__ == "__main__":
    # テスト
    manager = IssueManager()

    # テスト用Issue作成
    issue = manager.create_issue(
        title="HTTPクライアント重複",
        description="utils/api.tsとapi/client.tsの両方にHTTPクライアントが存在",
        category="architecture",
        severity="critical",
        location="src/frontend/src/utils/api.ts, src/frontend/src/api/client.ts",
        fix_suggestion="src/core/http/client.tsに統一",
    )

    print(f"Issue #{issue.id} created: {issue.title}")
    print(f"Open issues: {len(manager.get_open_issues())}")
